export const darkModeTheme = {
	id: 'dark-mode',
	name: 'Dark Mode',
	description: 'Low-light theme with green accents and neutral feedback states.',
	colorScheme: 'dark',
	previewColors: {
		page: '#0a0f0c',
		surface: '#111812',
		text: '#f7fbf8',
		muted: '#c4d3c9',
		accent: '#31c48d',
		border: '#34483b'
	},
	tokens: {
		'--color-page': '#0a0f0c',
		'--color-surface': '#111812',
		'--color-surface-muted': '#17261d',
		'--color-surface-subtle': '#1d2b23',
		'--color-text': '#f7fbf8',
		'--color-text-muted': '#c4d3c9',
		'--color-text-inverse': '#07100b',
		'--color-border': '#34483b',
		'--color-border-strong': '#6b8474',
		'--color-green': '#31c48d',
		'--color-green-hover': '#5ee1ad',
		'--color-green-soft': '#123421',
		'--color-green-border': '#2f8b61',
		'--color-critical-bg': '#262827',
		'--color-critical-border': '#f7fbf8',
		'--color-critical-text': '#f7fbf8',
		'--color-focus-ring': 'rgba(49, 196, 141, 0.38)',
		'--font-sans': "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
		'--font-size-xs': '0.75rem',
		'--font-size-sm': '0.875rem',
		'--font-size-md': '1rem',
		'--font-size-lg': '1.25rem',
		'--font-size-xl': '1.5rem',
		'--font-size-2xl': '2rem',
		'--font-size-3xl': '3rem',
		'--font-size-score': '4rem',
		'--font-weight-regular': '400',
		'--font-weight-medium': '650',
		'--font-weight-semibold': '750',
		'--font-weight-bold': '850',
		'--space-1': '0.25rem',
		'--space-2': '0.5rem',
		'--space-3': '0.75rem',
		'--space-4': '1rem',
		'--space-5': '1.25rem',
		'--space-6': '1.5rem',
		'--space-8': '2rem',
		'--space-10': '2.5rem',
		'--content-wide': '1180px',
		'--content-default': '1080px',
		'--content-readable': '760px',
		'--content-narrow': '720px',
		'--radius-sm': '6px',
		'--radius-md': '8px',
		'--radius-pill': '999px',
		'--border-width': '1px',
		'--border-width-strong': '2px',
		'--shadow-card': '0 12px 30px rgba(0, 0, 0, 0.28)',
		'--shadow-hover': '0 10px 24px rgba(0, 0, 0, 0.34)',
		'--shadow-focus': '0 0 0 3px var(--color-focus-ring)',
		'--motion-fast': '120ms',
		'--motion-medium': '180ms',
		'--motion-ease': 'ease'
	}
};
