export const defaultTheme = {
	id: 'default',
	name: 'Default',
	description: 'Original black, green, and white Quiz Lab palette.',
	colorScheme: 'light',
	previewColors: {
		page: '#f7faf8',
		surface: '#ffffff',
		text: '#111111',
		muted: '#5f6b62',
		accent: '#0f766e',
		border: '#d9e2dc'
	},
	tokens: {
		'--color-page': '#f7faf8',
		'--color-surface': '#ffffff',
		'--color-surface-muted': '#eef7f2',
		'--color-surface-subtle': '#f2f5f3',
		'--color-text': '#111111',
		'--color-text-muted': '#5f6b62',
		'--color-text-inverse': '#ffffff',
		'--color-border': '#d9e2dc',
		'--color-border-strong': '#9fb3a8',
		'--color-green': '#0f766e',
		'--color-green-hover': '#0b5d55',
		'--color-green-soft': '#e6f6f0',
		'--color-green-border': '#a8d8ce',
		'--color-critical-bg': '#f2f5f3',
		'--color-critical-border': '#111111',
		'--color-critical-text': '#111111',
		'--color-focus-ring': 'rgba(15, 118, 110, 0.24)',
		'--font-sans': "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
		'--font-size-xs': '0.75rem',
		'--font-size-sm': '0.875rem',
		'--font-size-md': '1rem',
		'--font-size-lg': '1.25rem',
		'--font-size-xl': '1.5rem',
		'--font-size-2xl': '2rem',
		'--font-size-3xl': '3rem',
		'--font-size-score': '4rem',
		'--font-weight-regular': '400',
		'--font-weight-medium': '650',
		'--font-weight-semibold': '750',
		'--font-weight-bold': '850',
		'--space-1': '0.25rem',
		'--space-2': '0.5rem',
		'--space-3': '0.75rem',
		'--space-4': '1rem',
		'--space-5': '1.25rem',
		'--space-6': '1.5rem',
		'--space-8': '2rem',
		'--space-10': '2.5rem',
		'--content-wide': '1180px',
		'--content-default': '1080px',
		'--content-readable': '760px',
		'--content-narrow': '720px',
		'--radius-sm': '6px',
		'--radius-md': '8px',
		'--radius-pill': '999px',
		'--border-width': '1px',
		'--border-width-strong': '2px',
		'--shadow-card': '0 12px 30px rgba(17, 17, 17, 0.06)',
		'--shadow-hover': '0 10px 24px rgba(17, 17, 17, 0.08)',
		'--shadow-focus': '0 0 0 3px var(--color-focus-ring)',
		'--motion-fast': '150ms',
		'--motion-medium': '250ms',
		'--motion-slow': '400ms',
		'--motion-ease-out': 'ease-out',
		'--motion-ease-in-out': 'ease-in-out',
		'--motion-ease': 'var(--motion-ease-out)',
		'--motion-duration-hover': 'var(--motion-fast)',
		'--motion-duration-focus': 'var(--motion-fast)',
		'--motion-duration-feedback': 'var(--motion-medium)',
		'--motion-duration-progress': 'var(--motion-medium)',
		'--motion-duration-entry': 'var(--motion-medium)',
		'--motion-duration-exit': 'var(--motion-fast)',
		'--motion-duration-loading': 'var(--motion-slow)',
		'--motion-ease-standard': 'var(--motion-ease-out)',
		'--motion-ease-emphasized': 'var(--motion-ease-in-out)'
	}
};
