export const highContrastTheme = {
	id: 'high-contrast',
	name: 'High Contrast',
	description: 'Maximum contrast theme with strong borders and green accents.',
	colorScheme: 'light',
	previewColors: {
		page: '#ffffff',
		surface: '#ffffff',
		text: '#000000',
		muted: '#1f1f1f',
		accent: '#005c45',
		border: '#000000'
	},
	tokens: {
		'--color-page': '#ffffff',
		'--color-surface': '#ffffff',
		'--color-surface-muted': '#effff5',
		'--color-surface-subtle': '#f5f5f5',
		'--color-text': '#000000',
		'--color-text-muted': '#1f1f1f',
		'--color-text-inverse': '#ffffff',
		'--color-border': '#000000',
		'--color-border-strong': '#000000',
		'--color-green': '#005c45',
		'--color-green-hover': '#003f30',
		'--color-green-soft': '#e8fff2',
		'--color-green-border': '#005c45',
		'--color-critical-bg': '#000000',
		'--color-critical-border': '#000000',
		'--color-critical-text': '#ffffff',
		'--color-focus-ring': 'rgba(0, 92, 69, 0.42)',
		'--font-sans': "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
		'--font-size-xs': '0.75rem',
		'--font-size-sm': '0.875rem',
		'--font-size-md': '1rem',
		'--font-size-lg': '1.25rem',
		'--font-size-xl': '1.5rem',
		'--font-size-2xl': '2rem',
		'--font-size-3xl': '3rem',
		'--font-size-score': '4rem',
		'--font-weight-regular': '400',
		'--font-weight-medium': '650',
		'--font-weight-semibold': '750',
		'--font-weight-bold': '850',
		'--space-1': '0.25rem',
		'--space-2': '0.5rem',
		'--space-3': '0.75rem',
		'--space-4': '1rem',
		'--space-5': '1.25rem',
		'--space-6': '1.5rem',
		'--space-8': '2rem',
		'--space-10': '2.5rem',
		'--content-wide': '1180px',
		'--content-default': '1080px',
		'--content-readable': '760px',
		'--content-narrow': '720px',
		'--radius-sm': '6px',
		'--radius-md': '8px',
		'--radius-pill': '999px',
		'--border-width': '1px',
		'--border-width-strong': '2px',
		'--shadow-card': '0 0 0 1px #000000',
		'--shadow-hover': '0 0 0 2px #005c45',
		'--shadow-focus': '0 0 0 3px var(--color-focus-ring)',
		'--motion-fast': '150ms',
		'--motion-medium': '250ms',
		'--motion-slow': '400ms',
		'--motion-ease-out': 'ease-out',
		'--motion-ease-in-out': 'ease-in-out',
		'--motion-ease': 'var(--motion-ease-out)',
		'--motion-duration-hover': 'var(--motion-fast)',
		'--motion-duration-focus': 'var(--motion-fast)',
		'--motion-duration-feedback': 'var(--motion-medium)',
		'--motion-duration-progress': 'var(--motion-medium)',
		'--motion-duration-entry': 'var(--motion-medium)',
		'--motion-duration-exit': 'var(--motion-fast)',
		'--motion-duration-loading': 'var(--motion-slow)',
		'--motion-ease-standard': 'var(--motion-ease-out)',
		'--motion-ease-emphasized': 'var(--motion-ease-in-out)'
	}
};
