export const purpleTheme = {
	id: 'purple',
	name: 'Purple',
	description: 'Deep violet surfaces with soft lavender accents.',
	colorScheme: 'dark',
	previewColors: {
		page: '#120b1f',
		surface: '#1c1230',
		text: '#fbf8ff',
		muted: '#d8cceb',
		accent: '#c8a2ff',
		border: '#4d3a69'
	},
	tokens: {
		'--color-page': '#120b1f',
		'--color-surface': '#1c1230',
		'--color-surface-muted': '#271a42',
		'--color-surface-subtle': '#31224f',
		'--color-text': '#fbf8ff',
		'--color-text-muted': '#d8cceb',
		'--color-text-inverse': '#160b2a',
		'--color-border': '#4d3a69',
		'--color-border-strong': '#9079b8',
		'--color-green': '#c8a2ff',
		'--color-green-hover': '#dfc9ff',
		'--color-green-soft': '#2d1b4b',
		'--color-green-border': '#8f68cc',
		'--color-critical-bg': '#2b2730',
		'--color-critical-border': '#fbf8ff',
		'--color-critical-text': '#fbf8ff',
		'--color-focus-ring': 'rgba(200, 162, 255, 0.4)',
		'--font-sans': "-apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
		'--font-size-xs': '0.75rem',
		'--font-size-sm': '0.875rem',
		'--font-size-md': '1rem',
		'--font-size-lg': '1.25rem',
		'--font-size-xl': '1.5rem',
		'--font-size-2xl': '2rem',
		'--font-size-3xl': '3rem',
		'--font-size-score': '4rem',
		'--font-weight-regular': '400',
		'--font-weight-medium': '650',
		'--font-weight-semibold': '750',
		'--font-weight-bold': '850',
		'--space-1': '0.25rem',
		'--space-2': '0.5rem',
		'--space-3': '0.75rem',
		'--space-4': '1rem',
		'--space-5': '1.25rem',
		'--space-6': '1.5rem',
		'--space-8': '2rem',
		'--space-10': '2.5rem',
		'--content-wide': '1180px',
		'--content-default': '1080px',
		'--content-readable': '760px',
		'--content-narrow': '720px',
		'--radius-sm': '6px',
		'--radius-md': '8px',
		'--radius-pill': '999px',
		'--border-width': '1px',
		'--border-width-strong': '2px',
		'--shadow-card': '0 12px 30px rgba(3, 0, 10, 0.32)',
		'--shadow-hover': '0 10px 24px rgba(3, 0, 10, 0.4)',
		'--shadow-focus': '0 0 0 3px var(--color-focus-ring)',
		'--motion-fast': '120ms',
		'--motion-medium': '180ms',
		'--motion-ease': 'ease'
	}
};
